server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1530849052Zmn,
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true # Baseline是指数据库非空状态下使用flyway首先执行的命令，用于创建 flyway_schema_history 表。

allow:
  origin: ${origin.url}
